import { App, Maker } from './types'

// Main makers data
const makers: Maker[] = [
  {
    id: '1',
    name: 'David Zafra',
    role: 'Entrepreneur & Product Designer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Passionate about creating beautiful and functional user interfaces.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-01-15',
    followers: 1200,
    twitter: 'davidzafra',
    github: 'davidzafra',
    website: 'https://davidzafra.design',
    linkedin: 'davidzafra'
  },
  {
    id: '2',
    name: 'Daniel Diestre',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'Building scalable web applications with modern technologies.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-02-01',
    followers: 850,
    twitter: 'danieldiestre',
    github: 'danieldiestre',
    website: 'https://danieldiestre.dev',
    linkedin: 'daniel-diestre'
  },
  {
    id: '3',
    name: 'Mike Johnson',
    role: 'Growth Marketing Manager',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Helping products reach their target audience effectively.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-10',
    followers: 650,
    twitter: 'mikejohnson',
    github: 'mikejohnson',
    website: 'https://mikejohnson.marketing',
    linkedin: 'mike-johnson-marketing'
  },
  {
    id: '4',
    name: 'Sarah Williams',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Creating delightful user experiences through thoughtful design.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-02-15',
    followers: 920,
    twitter: 'sarahw',
    website: 'https://sarahwilliams.design',
    github: 'sarahw',
    linkedin: 'sarah-williams-design'
  },
  {
    id: '5',
    name: 'David Chen',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Bridging the gap between business needs and user experience.',
    category: 'Other',
    makerCategory: 'Other',
    isVerified: true,
    joinedDate: '2024-01-20',
    followers: 1500,
    twitter: 'davidchen',
    website: 'https://davidchen.pm',
    linkedin: 'david-chen-pm',
    github: 'davidchen'
  }
]

// Additional mock makers for the makers page
export const ADDITIONAL_MAKERS: Maker[] = [
  {
    id: 'maker1',
    name: 'Emma Watson',
    role: 'UX Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating user-centered digital experiences with passion and precision.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-01-01',
    followers: 1500,
    twitter: 'emmawatson',
    website: 'https://emmawatson.design',
    linkedin: 'emma-watson-ux',
    github: 'emmawatsonux'
  },
  {
    id: 'maker2',
    name: 'Ryan Johnson',
    role: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Building scalable web applications with modern technologies.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: false,
    joinedDate: '2024-01-15',
    followers: 800,
    twitter: 'ryanjohnson',
    website: 'https://ryanjohnson.dev',
    linkedin: 'ryan-johnson-dev',
    github: 'ryanjohnsondev'
  },
  {
    id: 'maker3',
    name: 'Sophia Martinez',
    role: 'Growth Marketer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Driving user acquisition and retention through data-driven strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-02-01',
    followers: 1200,
    twitter: 'sophiamartinez',
    website: 'https://sophiamartinez.co',
    linkedin: 'sophia-martinez',
    github: 'sophiamartinez'
  },
  {
    id: 'maker10',
    name: 'Alex Rivera',
    role: 'Founder & Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop',
    bio: 'Crafting beautiful and responsive web interfaces.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-02-10',
    followers: 950,
    twitter: 'alexrivera',
    website: 'https://alexrivera.dev',
    linkedin: 'alex-rivera',
    github: 'alexrivera'
  },
  {
    id: 'maker11',
    name: 'Nina Patel',
    role: 'Product Marketing Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'Driving product growth through strategic marketing initiatives.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-02-15',
    followers: 780,
    twitter: 'ninapatel',
    website: 'https://ninapatel.marketing',
    linkedin: 'nina-patel',
    github: 'ninapatel'
  },
  {
    id: 'maker12',
    name: 'Marcus Chen',
    role: 'UI Designer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Creating delightful user interfaces with attention to detail.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-02-20',
    followers: 650,
    twitter: 'marcuschen',
    website: 'https://marcuschen.design',
    linkedin: 'marcus-chen',
    github: 'marcuschen'
  },
  {
    id: 'maker13',
    name: 'Sarah Lee',
    role: 'Backend Developer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Building robust and scalable backend systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-02-25',
    followers: 820,
    twitter: 'sarahlee',
    website: 'https://sarahlee.dev',
    linkedin: 'sarah-lee',
    github: 'sarahlee'
  },
  {
    id: 'maker14',
    name: 'James Wilson',
    role: 'Growth Hacker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Implementing data-driven growth strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-01',
    followers: 920,
    twitter: 'jameswilson',
    website: 'https://jameswilson.growth',
    linkedin: 'james-wilson',
    github: 'jameswilson'
  },
  {
    id: 'maker15',
    name: 'Emily Zhang',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Designing user-centric products that solve real problems.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-05',
    followers: 750,
    twitter: 'emilyzhang',
    website: 'https://emilyzhang.design',
    linkedin: 'emily-zhang',
    github: 'emilyzhang'
  },
  {
    id: 'maker16',
    name: 'Lucas Thompson',
    role: 'Mobile Developer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Crafting native mobile experiences that users love.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-07',
    followers: 680,
    twitter: 'lucasthompson',
    website: 'https://lucasthompson.dev',
    linkedin: 'lucas-thompson',
    github: 'lucasthompson'
  },
  {
    id: 'maker17',
    name: 'Isabella Rodriguez',
    role: 'Brand Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Creating memorable brand identities and visual experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-08',
    followers: 890,
    twitter: 'isabellar',
    website: 'https://isabellarodriguez.design',
    linkedin: 'isabella-rodriguez',
    github: 'isabellar'
  },
  {
    id: 'maker18',
    name: 'William Chang',
    role: 'DevOps Engineer',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
    bio: 'Automating deployment pipelines and optimizing infrastructure.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: false,
    joinedDate: '2024-03-09',
    followers: 720,
    twitter: 'willchangdev',
    website: 'https://williamchang.dev',
    linkedin: 'william-chang',
    github: 'willchangdev'
  },
  {
    id: 'maker19',
    name: 'Olivia Foster',
    role: 'Content Strategist',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Developing content strategies that drive engagement.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-10',
    followers: 850,
    twitter: 'oliviafoster',
    website: 'https://oliviafoster.co',
    linkedin: 'olivia-foster',
    github: 'oliviafoster'
  },
  {
    id: 'maker20',
    name: 'Ethan Brooks',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop',
    bio: 'Solving complex problems through intuitive design solutions.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-11',
    followers: 920,
    twitter: 'ethanbrooks',
    website: 'https://ethanbrooks.design',
    linkedin: 'ethan-brooks',
    github: 'ethanbrooks'
  },
  {
    id: 'maker21',
    name: 'Sophie Anderson',
    role: 'SEO Specialist',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop',
    bio: 'Optimizing digital presence for maximum visibility.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-12',
    followers: 760,
    twitter: 'sophieanderson',
    website: 'https://sophieanderson.seo',
    linkedin: 'sophie-anderson',
    github: 'sophieanderson'
  },
  {
    id: 'maker22',
    name: 'Daniel Kim',
    role: 'Co-founder & Blockchain Developer',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Building decentralized applications for the future.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-13',
    followers: 1100,
    twitter: 'danielkim',
    website: 'https://danielkim.dev',
    linkedin: 'daniel-kim',
    github: 'danielkim'
  },
  {
    id: 'maker23',
    name: 'Rachel Green',
    role: 'Motion Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating engaging animations and interactive experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-14',
    followers: 840,
    twitter: 'rachelgreen',
    website: 'https://rachelgreen.design',
    linkedin: 'rachel-green',
    github: 'rachelgreen'
  },
  {
    id: 'maker24',
    name: 'Thomas Wright',
    role: 'Cloud Architect',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Designing scalable cloud infrastructure solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-15',
    followers: 950,
    twitter: 'thomaswright',
    website: 'https://thomaswright.cloud',
    linkedin: 'thomas-wright',
    github: 'thomaswright'
  },
  {
    id: 'maker25',
    name: 'Maria Garcia',
    role: 'Community Manager',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Building and nurturing engaged online communities.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-16',
    followers: 880,
    twitter: 'mariagarcia',
    website: 'https://mariagarcia.community',
    linkedin: 'maria-garcia',
  },
  {
    id: 'maker26',
    name: 'Andrew Wilson',
    role: 'Game Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Creating immersive gaming experiences.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-17',
    followers: 1200,
    twitter: 'andrewwilson',
    website: 'https://andrewwilson.games',
    linkedin: 'andrew-wilson',
    github: 'andrewwilson'
  },
  {
    id: 'maker27',
    name: 'Laura Martinez',
    role: 'UX Researcher',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Understanding user behavior through research.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-18',
    followers: 780,
    twitter: 'lauramartinez',
    website: 'https://lauramartinez.research',
    linkedin: 'laura-martinez',
    github: 'lauramartinez'
  },
  {
    id: 'maker28',
    name: 'Kevin Lee',
    role: 'Founder & AI Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Developing AI solutions for real-world problems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-19',
    followers: 1500,
    twitter: 'kevinlee',
    website: 'https://kevinlee.ai',
    linkedin: 'kevin-lee',
    github: 'kevinlee'
  },
  {
    id: 'maker29',
    name: 'Hannah Brown',
    role: 'Digital Marketing',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Driving growth through digital marketing strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-20',
    followers: 920,
    twitter: 'hannahbrown',
    website: 'https://hannahbrown.marketing',
    linkedin: 'hannah-brown',
    github: 'hannahbrown'
  },
  {
    id: 'maker30',
    name: 'Michael Chen',
    role: 'Systems Architect',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Designing robust and scalable systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-21',
    followers: 1100,
    twitter: 'michaelchen',
    website: 'https://michaelchen.dev',
    linkedin: 'michael-chen',
    github: 'michaelchen'
  },
  {
    id: 'maker31',
    name: 'Victoria Adams',
    role: 'Product Marketing',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Launching products that users love.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-22',
    followers: 850,
    twitter: 'victoriaadams',
    website: 'https://victoriaadams.marketing',
    linkedin: 'victoria-adams',
    github: 'victoriaadams'
  },
  {
    id: 'maker32',
    name: 'Christopher Lee',
    role: 'Security Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Securing applications and infrastructure.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-23',
    followers: 980,
    twitter: 'chrislee',
    website: 'https://chrislee.security',
    linkedin: 'christopher-lee',
    github: 'chrislee'
  },
  {
    id: 'maker33',
    name: 'Sophia Wang',
    role: 'Interaction Designer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Creating delightful interactive experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-24',
    followers: 760,
    twitter: 'sophiawang',
    website: 'https://sophiawang.design',
    linkedin: 'sophia-wang',
    github: 'sophiawang'
  },
  {
    id: 'maker34',
    name: 'Robert Taylor',
    role: 'Growth Hacker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Driving exponential growth through data.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-25',
    followers: 890,
    twitter: 'roberttaylor',
    website: 'https://roberttaylor.growth',
    linkedin: 'robert-taylor',
    github: 'roberttaylor'
  },
  {
    id: 'maker35',
    name: 'Emma Davis',
    role: 'Frontend Engineer',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Building beautiful and performant web interfaces.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-26',
    followers: 720,
    twitter: 'emmadavis',
    website: 'https://emmadavis.dev',
    linkedin: 'emma-davis',
    github: 'emmadavis'
  },
  {
    id: 'maker36',
    name: 'Daniel Kim',
    role: 'Mobile Developer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Crafting native mobile experiences.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-27',
    followers: 940,
    twitter: 'danielkim',
    website: 'https://danielkim.dev',
    linkedin: 'daniel-kim',
    github: 'danielkim'
  },
  {
    id: 'maker37',
    name: 'Rachel Green',
    role: 'Content Strategist',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'Creating content that converts.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-28',
    followers: 830,
    twitter: 'rachelgreen',
    website: 'https://rachelgreen.content',
    linkedin: 'rachel-green',
    github: 'rachelgreen'
  },
  {
    id: 'maker38',
    name: 'James Wilson',
    role: 'DevOps Engineer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Automating deployment pipelines.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-29',
    followers: 1100,
    twitter: 'jameswilson',
    website: 'https://jameswilson.dev',
    linkedin: 'james-wilson',
    github: 'jameswilson'
  },
  {
    id: 'maker39',
    name: 'Isabella Martinez',
    role: 'UI Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Designing intuitive interfaces.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-03-30',
    followers: 750,
    twitter: 'isabellamtz',
    website: 'https://isabellamartinez.design',
    linkedin: 'isabella-martinez',
    github: 'isabellamtz'
  },
  {
    id: 'maker40',
    name: 'Thomas Anderson',
    role: 'Backend Engineer',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Building scalable backend systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-31',
    followers: 920,
    twitter: 'tanderson',
    website: 'https://tanderson.dev',
    linkedin: 'thomas-anderson',
    github: 'tanderson'
  },
  {
    id: 'maker41',
    name: 'Olivia Brown',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Creating user-centered products.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-04-01',
    followers: 880,
    twitter: 'oliviabrown',
    website: 'https://oliviabrown.design',
    linkedin: 'olivia-brown',
    github: 'oliviabrown'
  },
  {
    id: 'maker42',
    name: 'William Zhang',
    role: 'Data Scientist',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
    bio: 'Turning data into insights.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-02',
    followers: 1050,
    twitter: 'williamzhang',
    website: 'https://williamzhang.ai',
    linkedin: 'william-zhang',
    github: 'williamzhang'
  },
  {
    id: 'maker43',
    name: 'Sophie Turner',
    role: 'Brand Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating memorable brand identities.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-04-03',
    followers: 790,
    twitter: 'sophieturner',
    website: 'https://sophieturner.design',
    linkedin: 'sophie-turner',
    github: 'sophieturner'
  },
  {
    id: 'maker44',
    name: 'Lucas Rodriguez',
    role: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Building end-to-end solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-04',
    followers: 970,
    twitter: 'lucasrodriguez',
    website: 'https://lucasrodriguez.dev',
    linkedin: 'lucas-rodriguez',
    github: 'lucasrodriguez'
  },
  {
    id: 'maker45',
    name: 'Ava Thompson',
    role: 'Growth Manager',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Scaling products and teams.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-04-05',
    followers: 840,
    twitter: 'avathompson',
    website: 'https://avathompson.growth',
    linkedin: 'ava-thompson',
    github: 'avathompson'
  },
  {
    id: 'maker46',
    name: 'Nathan Park',
    role: 'Cloud Architect',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Designing cloud-native solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-06',
    followers: 1150,
    twitter: 'nathanpark',
    website: 'https://nathanpark.cloud',
    linkedin: 'nathan-park',
    github: 'nathanpark'
  },
  {
    id: 'maker47',
    name: 'Maya Patel',
    role: 'UX Researcher',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'Understanding user behavior.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-04-07',
    followers: 730,
    twitter: 'mayapatel',
    website: 'https://mayapatel.research',
    linkedin: 'maya-patel',
    github: 'mayapatel'
  },
  {
    id: 'maker48',
    name: 'Benjamin Lee',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Shipping impactful products.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-04-08',
    followers: 960,
    twitter: 'benjaminlee',
    website: 'https://benjaminlee.product',
    linkedin: 'benjamin-lee',
    github: 'benjaminlee'
  },
  {
    id: 'maker49',
    name: 'Grace Chen',
    role: 'Motion Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Creating engaging animations.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-04-09',
    followers: 820,
    twitter: 'gracechen',
    website: 'https://gracechen.design',
    linkedin: 'grace-chen',
    github: 'gracechen'
  },
  {
    id: 'maker50',
    name: 'Alexander White',
    role: 'Security Analyst',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Protecting digital assets.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-10',
    followers: 890,
    twitter: 'alexwhite',
    website: 'https://alexwhite.security',
    linkedin: 'alexander-white',
    github: 'alexwhite'
  }
]

// Mock data for UI only - will be replaced with real data fetching
export const MOCK_APPS: App[] = [
  {
    id: '1',
    name: 'BrowserAgent',
    description: 'Browser-based AI agents - unlimited runs, fixed cost.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/chrome/chrome.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 345,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 24,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      website: 'https://browseragent.example.com',
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'maker-john',
        name: 'John Doe',
        role: 'Founder & Product Designer',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
      {
        id: 'maker-jane',
        name: 'Jane Smith',
        role: 'Full Stack Developer',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
        bio: 'Building scalable web applications with modern technologies.',
        category: 'Developer',
        joinedDate: '2024-02-01',
        followers: 850,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 12500,
      activeUsers: 5300,
      avgRating: 4.8,
    }
  },
  {
    id: '2',
    name: 'Gemini Personalization',
    description: 'Get help made just for you.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/google/google.png',
    coverImage: 'https://picsum.photos/1920/400?random=2',
    screenshots: [
      'https://picsum.photos/800/450?random=21',
      'https://picsum.photos/800/450?random=22',
      'https://picsum.photos/800/450?random=23',
    ],
    votes: 243,
    tags: ['Artificial Intelligence', 'Search'],
    commentsCount: 3,
    badges: ['new'],
    technologies: ['Python', 'PyTorch', 'TensorFlow', 'Google Cloud'],
    launchDate: '2024-01-20',
    updates: [
      { date: '2024-02-28', version: '1.0.1', description: 'Improved response accuracy and reduced latency' },
    ],
    externalLinks: {
      website: 'https://gemini-personalization.example.com',
    },
    makers: [
      {
        id: 'maker-sarah',
        name: 'Sarah Williams',
        role: 'UI/UX Designer',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        bio: 'Creating delightful user experiences through thoughtful design.',
        category: 'Designer',
        joinedDate: '2024-02-15',
        followers: 920,
        isVerified: true
      },
      {
        id: 'maker-david',
        name: 'David Chen',
        role: 'Product Manager',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        bio: 'Bridging the gap between business needs and user experience.',
        category: 'Other',
        joinedDate: '2024-01-20',
        followers: 1500,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 35000,
      avgRating: 4.6,
    }
  },
  {
    id: '3',
    name: 'GrammarPaw',
    description: 'AI writing assistant for Mac. GrammarPaw uses advanced machine learning algorithms to analyze your writing and suggest improvements to grammar, style, and clarity. It integrates seamlessly with all major writing applications on macOS.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/markdown/markdown.png',
    coverImage: 'https://picsum.photos/1920/400?random=3',
    screenshots: [
      'https://picsum.photos/800/450?random=31',
      'https://picsum.photos/800/450?random=32',
    ],
    votes: 200,
    tags: ['Productivity', 'User Experience', 'Tech'],
    commentsCount: 9,
    badges: ['top'],
    technologies: ['Swift', 'Core ML', 'Natural Language Processing'],
    launchDate: '2023-09-05',
    updates: [
      { date: '2023-11-10', version: '1.1.0', description: 'Added support for additional languages' },
      { date: '2024-01-20', version: '1.2.0', description: 'Improved performance and reduced memory usage' },
    ],
    externalLinks: {
      website: 'https://grammarpaw.example.com',
      appStore: 'https://apps.apple.com/example-grammarpaw',
    },
    makers: [
      {
        id: 'maker-david',
        name: 'David Kim',
        role: 'Founder',
        avatar: '/avatars/avatar-4.png',
        bio: 'Building innovative language tools for developers',
        category: 'Developer',
        joinedDate: '2023-12-01',
        followers: 750,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 8700,
      avgRating: 4.7,
    }
  },
  {
    id: '4',
    name: 'Interlify',
    description: 'Connect your APIs to LLMs in minutes. Interlify provides a no-code platform to integrate your existing APIs with large language models, enabling advanced AI capabilities with minimal development effort.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/json/json.png',
    coverImage: 'https://picsum.photos/1920/400?random=4',
    screenshots: [
      'https://picsum.photos/800/450?random=41',
      'https://picsum.photos/800/450?random=42',
      'https://picsum.photos/800/450?random=43',
    ],
    votes: 193,
    tags: ['SaaS', 'Developer Tools', 'Artificial Intelligence'],
    commentsCount: 17,
    technologies: ['JavaScript', 'Python', 'Docker', 'Kubernetes'],
    launchDate: '2023-11-01',
    updates: [
      { date: '2024-01-15', version: '1.1.0', description: 'Added support for advanced authentication methods' },
    ],
    externalLinks: {
      website: 'https://interlify.example.com',
      github: 'https://github.com/example/interlify',
    },
    makers: [
      {
        id: 'maker-sarah',
        name: 'Sarah Johnson',
        role: 'Co-founder',
        avatar: '/avatars/avatar-5.png',
        bio: 'Marketing expert with a passion for AI',
        category: 'Marketing',
        joinedDate: '2023-11-15',
        followers: 920,
        isVerified: true
      },
      {
        id: 'maker-michael',
        name: 'Michael Lee',
        role: 'Co-founder',
        avatar: '/avatars/avatar-6.png',
        bio: 'Full-stack developer specializing in AI integrations',
        category: 'Developer',
        joinedDate: '2023-11-15',
        followers: 840,
        isVerified: false
      }
    ],
    metrics: {
      activeUsers: 2800,
    }
  },
  {
    id: '5',
    name: 'Direct Sponsorships by beehiiv',
    description: 'Selling ads any other way is selling yourself short. Direct Sponsorships provides newsletter creators with a streamlined platform to manage sponsorships, negotiate with advertisers, and maximize revenue from their audience.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/telegram/telegram.png',
    coverImage: 'https://picsum.photos/1920/400?random=5',
    screenshots: [
      'https://picsum.photos/800/450?random=51',
      'https://picsum.photos/800/450?random=52',
    ],
    votes: 177,
    tags: ['Newsletters', 'Growth Hacking', 'Advertising'],
    commentsCount: 5,
    badges: ['new'],
    technologies: ['React', 'Next.js', 'Node.js', 'PostgreSQL'],
    launchDate: '2024-02-01',
    externalLinks: {
      website: 'https://directsponsorships.example.com',
    },
    makers: [
      {
        id: 'maker-tyler',
        name: 'Tyler Wilson',
        role: 'Product Manager',
        avatar: '/avatars/avatar-7.png',
        bio: 'Product leader focused on creator economy',
        category: 'Marketing',
        joinedDate: '2024-01-10',
        followers: 680,
        isVerified: false
      }
    ],
    metrics: {
      activeUsers: 1200,
    }
  },
  {
    id: '6',
    name: 'DevFlow',
    description: 'AI-powered development workflow assistant. DevFlow analyzes your coding patterns and automates repetitive tasks, helping you focus on what matters.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/visual-studio-code/visual-studio-code.png',
    coverImage: 'https://picsum.photos/1920/400?random=6',
    screenshots: [
      'https://picsum.photos/800/450?random=61',
      'https://picsum.photos/800/450?random=62',
    ],
    votes: 165,
    tags: ['Developer Tools', 'Productivity', 'AI'],
    commentsCount: 12,
    badges: ['trending'],
    technologies: ['TypeScript', 'Python', 'Machine Learning'],
    launchDate: '2024-01-05',
    externalLinks: {
      website: 'https://devflow.example.com',
      github: 'https://github.com/example/devflow',
    },
    makers: [
      {
        id: 'maker-alex',
        name: 'Alex Rivera',
        role: 'Founder & Frontend Developer',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop',
        bio: 'Frontend developer passionate about developer tools',
        category: 'Developer',
        joinedDate: '2024-01-05',
        followers: 950,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 3500,
      avgRating: 4.9,
    }
  },
  {
    id: '7',
    name: 'DesignVault',
    description: 'Your personal design inspiration library. Save, organize, and share design inspiration from across the web.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/css/css.png',
    coverImage: 'https://picsum.photos/1920/400?random=7',
    screenshots: [
      'https://picsum.photos/800/450?random=71',
      'https://picsum.photos/800/450?random=72',
    ],
    votes: 142,
    tags: ['Design', 'Productivity', 'Collaboration'],
    commentsCount: 8,
    technologies: ['React', 'Firebase', 'TailwindCSS'],
    launchDate: '2024-02-10',
    externalLinks: {
      website: 'https://designvault.example.com',
      appStore: 'https://apps.apple.com/example-designvault',
    },
    makers: [
      {
        id: 'maker-sophia',
        name: 'Sophia Wang',
        role: 'Interaction Designer',
        avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        bio: 'Creating delightful interactive experiences',
        category: 'Designer',
        joinedDate: '2024-02-10',
        followers: 760,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 5200,
      avgRating: 4.7,
    }
  },
  {
    id: '8',
    name: 'TaskMaster Pro',
    description: 'Advanced task management for power users. Features include natural language processing, AI task prioritization, and smart scheduling.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png',
    coverImage: 'https://picsum.photos/1920/400?random=8',
    screenshots: [
      'https://picsum.photos/800/450?random=81',
      'https://picsum.photos/800/450?random=82',
    ],
    votes: 198,
    tags: ['Productivity', 'AI', 'Task Management'],
    commentsCount: 15,
    badges: ['top'],
    technologies: ['React Native', 'Node.js', 'MongoDB'],
    launchDate: '2024-01-15',
    externalLinks: {
      website: 'https://taskmaster.example.com',
      appStore: 'https://apps.apple.com/example-taskmaster',
      playStore: 'https://play.google.com/store/example-taskmaster',
    },
    makers: [
      {
        id: 'maker-william',
        name: 'William Zhang',
        role: 'Data Scientist',
        avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
        bio: 'Turning data into insights',
        category: 'Developer',
        joinedDate: '2024-01-15',
        followers: 1050,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 15000,
      activeUsers: 8200,
      avgRating: 4.8,
    }
  },
  {
    id: '9',
    name: 'SocialBoost',
    description: 'AI-powered social media management platform. Schedule posts, analyze engagement, and grow your audience with smart recommendations.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/twitter/twitter.png',
    coverImage: 'https://picsum.photos/1920/400?random=9',
    screenshots: [
      'https://picsum.photos/800/450?random=91',
      'https://picsum.photos/800/450?random=92',
    ],
    votes: 156,
    tags: ['Social Media', 'Marketing', 'AI'],
    commentsCount: 11,
    technologies: ['Vue.js', 'Python', 'PostgreSQL'],
    launchDate: '2024-02-20',
    externalLinks: {
      website: 'https://socialboost.example.com',
    },
    makers: [
      {
        id: 'maker-ava',
        name: 'Ava Thompson',
        role: 'Growth Manager',
        avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        bio: 'Scaling products and teams',
        category: 'Marketing',
        joinedDate: '2024-02-20',
        followers: 840,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 4200,
      avgRating: 4.6,
    }
  },
  {
    id: '10',
    name: 'CodeBuddy',
    description: 'Your AI pair programming companion. Get real-time code suggestions, refactoring tips, and bug detection as you code.',
    imageUrl: 'https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png',
    coverImage: 'https://picsum.photos/1920/400?random=10',
    screenshots: [
      'https://picsum.photos/800/450?random=101',
      'https://picsum.photos/800/450?random=102',
    ],
    votes: 225,
    tags: ['Developer Tools', 'AI', 'Productivity'],
    commentsCount: 18,
    badges: ['trending'],
    technologies: ['TypeScript', 'Python', 'OpenAI'],
    launchDate: '2024-03-01',
    externalLinks: {
      website: 'https://codebuddy.example.com',
      github: 'https://github.com/example/codebuddy',
    },
    makers: [
      {
        id: 'maker-nathan',
        name: 'Nathan Park',
        role: 'Cloud Architect',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        bio: 'Designing cloud-native solutions',
        category: 'Developer',
        joinedDate: '2024-03-01',
        followers: 1150,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 6800,
      avgRating: 4.9,
    }
  }
]

// Helper functions
export function getAllMakers(): Maker[] {
  return [...makers, ...ADDITIONAL_MAKERS]
}

export function getMakersByCategory(category: string): Maker[] {
  const allMakers = getAllMakers()
  if (category === 'All') return allMakers
  return allMakers.filter(maker => maker.category === category)
}

export function getAppById(id: string): App | undefined {
  return MOCK_APPS.find(app => app.id === id)
}

export function getAllApps(): App[] {
  return [...MOCK_APPS]
}

export function getTopApps(limit: number = 5): App[] {
  return [...MOCK_APPS]
    .sort((a, b) => b.votes - a.votes)
    .slice(0, limit)
} 