import { App, Maker } from './types'

// Main makers data
const makers: Maker[] = [
  {
    id: '1',
    name: 'David Zafra',
    role: 'Entrepreneur & Product Designer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Passionate about creating beautiful and functional user interfaces.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-01-15',
    followers: 1200,
    twitter: 'davidzafra',
    github: 'davidzafra',
    website: 'https://davidzafra.design',
    linkedin: 'davidzafra'
  },
  {
    id: '2',
    name: 'Dani Diestre',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'Building scalable web applications with modern technologies.',
    category: 'Product Manager',
    makerCategory: 'Product Manager',
    isVerified: true,
    joinedDate: '2024-02-01',
    followers: 850,
    twitter: 'danieldiestre',
    github: 'danidiestre',
    website: 'https://danieldiestre.dev',
    linkedin: 'danidiestre'
  },
  {
    id: '3',
    name: 'Saul Mases',
    role: 'Digital Product Designer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Making design feasible and aligned with business goals and user needs.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-04-01',
    followers: 666,
    twitter: 'saulmases',
    github: 'saulmases',
    website: 'https://saulmases.com',
    linkedin: 'saulmases',
    dribbble: 'saulmases'
  },
  {
    id: '4',
    name: 'Sarah Williams',
    role: 'UI/UX Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Creating delightful user experiences through thoughtful design.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-02-15',
    followers: 920,
    twitter: 'sarahw',
    website: 'https://sarahwilliams.design',
    github: 'sarahw',
    linkedin: 'sarah-williams-design'
  },
  {
    id: '5',
    name: 'David Chen',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Bridging the gap between business needs and user experience.',
    category: 'Other',
    makerCategory: 'Other',
    isVerified: true,
    joinedDate: '2024-01-20',
    followers: 1500,
    twitter: 'davidchen',
    website: 'https://davidchen.pm',
    linkedin: 'david-chen-pm',
    github: 'davidchen'
  }
]

// Additional mock makers for the makers page
export const ADDITIONAL_MAKERS: Maker[] = [
  {
    id: 'maker1',
    name: 'Emma Watson',
    role: 'UX Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating user-centered digital experiences with passion and precision.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-01-01',
    followers: 1500,
    twitter: 'emmawatson',
    website: 'https://emmawatson.design',
    linkedin: 'emma-watson-ux',
    github: 'emmawatsonux'
  },
  {
    id: 'maker2',
    name: 'Ryan Johnson',
    role: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Building scalable web applications with modern technologies.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: false,
    joinedDate: '2024-01-15',
    followers: 800,
    twitter: 'ryanjohnson',
    website: 'https://ryanjohnson.dev',
    linkedin: 'ryan-johnson-dev',
    github: 'ryanjohnsondev'
  },
  {
    id: 'maker3',
    name: 'Sophia Martinez',
    role: 'Growth Marketer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Driving user acquisition and retention through data-driven strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-02-01',
    followers: 1200,
    twitter: 'sophiamartinez',
    website: 'https://sophiamartinez.co',
    linkedin: 'sophia-martinez',
    github: 'sophiamartinez'
  },
  {
    id: 'maker10',
    name: 'Alex Rivera',
    role: 'Founder & Frontend Developer',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop',
    bio: 'Crafting beautiful and responsive web interfaces.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-02-10',
    followers: 950,
    twitter: 'alexrivera',
    website: 'https://alexrivera.dev',
    linkedin: 'alex-rivera',
    github: 'alexrivera'
  },
  {
    id: 'maker11',
    name: 'Nina Patel',
    role: 'Product Marketing Manager',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    bio: 'Driving product growth through strategic marketing initiatives.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-02-15',
    followers: 780,
    twitter: 'ninapatel',
    website: 'https://ninapatel.marketing',
    linkedin: 'nina-patel',
    github: 'ninapatel'
  },
  {
    id: 'maker12',
    name: 'Marcus Chen',
    role: 'UI Designer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Creating delightful user interfaces with attention to detail.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-02-20',
    followers: 650,
    twitter: 'marcuschen',
    website: 'https://marcuschen.design',
    linkedin: 'marcus-chen',
    github: 'marcuschen'
  },
  {
    id: 'maker13',
    name: 'Sarah Lee',
    role: 'Backend Developer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Building robust and scalable backend systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-02-25',
    followers: 820,
    twitter: 'sarahlee',
    website: 'https://sarahlee.dev',
    linkedin: 'sarah-lee',
    github: 'sarahlee'
  },
  {
    id: 'maker14',
    name: 'James Wilson',
    role: 'Growth Hacker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Implementing data-driven growth strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-01',
    followers: 920,
    twitter: 'jameswilson',
    website: 'https://jameswilson.growth',
    linkedin: 'james-wilson',
    github: 'jameswilson'
  },
  {
    id: 'maker15',
    name: 'Emily Zhang',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Designing user-centric products that solve real problems.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-05',
    followers: 750,
    twitter: 'emilyzhang',
    website: 'https://emilyzhang.design',
    linkedin: 'emily-zhang',
    github: 'emilyzhang'
  },
  {
    id: 'maker16',
    name: 'Lucas Thompson',
    role: 'Mobile Developer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Crafting native mobile experiences that users love.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-07',
    followers: 680,
    twitter: 'lucasthompson',
    website: 'https://lucasthompson.dev',
    linkedin: 'lucas-thompson',
    github: 'lucasthompson'
  },
  {
    id: 'maker17',
    name: 'Isabella Rodriguez',
    role: 'Brand Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Creating memorable brand identities and visual experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-08',
    followers: 890,
    twitter: 'isabellar',
    website: 'https://isabellarodriguez.design',
    linkedin: 'isabella-rodriguez',
    github: 'isabellar'
  },
  {
    id: 'maker18',
    name: 'William Chang',
    role: 'DevOps Engineer',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
    bio: 'Automating deployment pipelines and optimizing infrastructure.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: false,
    joinedDate: '2024-03-09',
    followers: 720,
    twitter: 'willchangdev',
    website: 'https://williamchang.dev',
    linkedin: 'william-chang',
    github: 'willchangdev'
  },
  {
    id: 'maker19',
    name: 'Olivia Foster',
    role: 'Content Strategist',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Developing content strategies that drive engagement.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-10',
    followers: 850,
    twitter: 'oliviafoster',
    website: 'https://oliviafoster.co',
    linkedin: 'olivia-foster',
    github: 'oliviafoster'
  },
  {
    id: 'maker20',
    name: 'Ethan Brooks',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop',
    bio: 'Solving complex problems through intuitive design solutions.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-11',
    followers: 920,
    twitter: 'ethanbrooks',
    website: 'https://ethanbrooks.design',
    linkedin: 'ethan-brooks',
    github: 'ethanbrooks'
  },
  {
    id: 'maker21',
    name: 'Sophie Anderson',
    role: 'SEO Specialist',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=400&h=400&fit=crop',
    bio: 'Optimizing digital presence for maximum visibility.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-12',
    followers: 760,
    twitter: 'sophieanderson',
    website: 'https://sophieanderson.seo',
    linkedin: 'sophie-anderson',
    github: 'sophieanderson'
  },
  {
    id: 'maker22',
    name: 'Daniel Kim',
    role: 'Co-founder & Blockchain Developer',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Building decentralized applications for the future.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-13',
    followers: 1100,
    twitter: 'danielkim',
    website: 'https://danielkim.dev',
    linkedin: 'daniel-kim',
    github: 'danielkim'
  },
  {
    id: 'maker23',
    name: 'Rachel Green',
    role: 'Motion Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating engaging animations and interactive experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-14',
    followers: 840,
    twitter: 'rachelgreen',
    website: 'https://rachelgreen.design',
    linkedin: 'rachel-green',
    github: 'rachelgreen'
  },
  {
    id: 'maker24',
    name: 'Thomas Wright',
    role: 'Cloud Architect',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Designing scalable cloud infrastructure solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-15',
    followers: 950,
    twitter: 'thomaswright',
    website: 'https://thomaswright.cloud',
    linkedin: 'thomas-wright',
    github: 'thomaswright'
  },
  {
    id: 'maker25',
    name: 'Maria Garcia',
    role: 'Community Manager',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Building and nurturing engaged online communities.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-16',
    followers: 880,
    twitter: 'mariagarcia',
    website: 'https://mariagarcia.community',
    linkedin: 'maria-garcia',
  },
  {
    id: 'maker26',
    name: 'Andrew Wilson',
    role: 'Game Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Creating immersive gaming experiences.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-17',
    followers: 1200,
    twitter: 'andrewwilson',
    website: 'https://andrewwilson.games',
    linkedin: 'andrew-wilson',
    github: 'andrewwilson'
  },
  {
    id: 'maker27',
    name: 'Laura Martinez',
    role: 'UX Researcher',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Understanding user behavior through research.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-18',
    followers: 780,
    twitter: 'lauramartinez',
    website: 'https://lauramartinez.research',
    linkedin: 'laura-martinez',
    github: 'lauramartinez'
  },
  {
    id: 'maker28',
    name: 'Kevin Lee',
    role: 'Founder & AI Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Developing AI solutions for real-world problems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-19',
    followers: 1500,
    twitter: 'kevinlee',
    website: 'https://kevinlee.ai',
    linkedin: 'kevin-lee',
    github: 'kevinlee'
  },
  {
    id: 'maker29',
    name: 'Hannah Brown',
    role: 'Digital Marketing',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Driving growth through digital marketing strategies.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-20',
    followers: 920,
    twitter: 'hannahbrown',
    website: 'https://hannahbrown.marketing',
    linkedin: 'hannah-brown',
    github: 'hannahbrown'
  },
  {
    id: 'maker30',
    name: 'Michael Chen',
    role: 'Systems Architect',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Designing robust and scalable systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-21',
    followers: 1100,
    twitter: 'michaelchen',
    website: 'https://michaelchen.dev',
    linkedin: 'michael-chen',
    github: 'michaelchen'
  },
  {
    id: 'maker31',
    name: 'Victoria Adams',
    role: 'Product Marketing',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Launching products that users love.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-22',
    followers: 850,
    twitter: 'victoriaadams',
    website: 'https://victoriaadams.marketing',
    linkedin: 'victoria-adams',
    github: 'victoriaadams'
  },
  {
    id: 'maker32',
    name: 'Christopher Lee',
    role: 'Security Engineer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Securing applications and infrastructure.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-23',
    followers: 980,
    twitter: 'chrislee',
    website: 'https://chrislee.security',
    linkedin: 'christopher-lee',
    github: 'chrislee'
  },
  {
    id: 'maker33',
    name: 'Sophia Wang',
    role: 'Interaction Designer',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Creating delightful interactive experiences.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-03-24',
    followers: 760,
    twitter: 'sophiawang',
    website: 'https://sophiawang.design',
    linkedin: 'sophia-wang',
    github: 'sophiawang'
  },
  {
    id: 'maker34',
    name: 'Robert Taylor',
    role: 'Growth Hacker',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Driving exponential growth through data.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: false,
    joinedDate: '2024-03-25',
    followers: 890,
    twitter: 'roberttaylor',
    website: 'https://roberttaylor.growth',
    linkedin: 'robert-taylor',
    github: 'roberttaylor'
  },
  {
    id: 'maker35',
    name: 'Emma Davis',
    role: 'Frontend Engineer',
    avatar: 'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?w=400&h=400&fit=crop',
    bio: 'Building beautiful and performant web interfaces.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-26',
    followers: 720,
    twitter: 'emmadavis',
    website: 'https://emmadavis.dev',
    linkedin: 'emma-davis',
    github: 'emmadavis'
  },
  {
    id: 'maker36',
    name: 'Daniel Kim',
    role: 'Mobile Developer',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Crafting native mobile experiences.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-27',
    followers: 940,
    twitter: 'danielkim',
    website: 'https://danielkim.dev',
    linkedin: 'daniel-kim',
    github: 'danielkim'
  },
  {
    id: 'maker37',
    name: 'Rachel Green',
    role: 'Content Strategist',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'Creating content that converts.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-03-28',
    followers: 830,
    twitter: 'rachelgreen',
    website: 'https://rachelgreen.content',
    linkedin: 'rachel-green',
    github: 'rachelgreen'
  },
  {
    id: 'maker38',
    name: 'James Wilson',
    role: 'DevOps Engineer',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Automating deployment pipelines.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-29',
    followers: 1100,
    twitter: 'jameswilson',
    website: 'https://jameswilson.dev',
    linkedin: 'james-wilson',
    github: 'jameswilson'
  },
  {
    id: 'maker39',
    name: 'Isabella Martinez',
    role: 'UI Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Designing intuitive interfaces.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-03-30',
    followers: 750,
    twitter: 'isabellamtz',
    website: 'https://isabellamartinez.design',
    linkedin: 'isabella-martinez',
    github: 'isabellamtz'
  },
  {
    id: 'maker40',
    name: 'Thomas Anderson',
    role: 'Backend Engineer',
    avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&h=400&fit=crop',
    bio: 'Building scalable backend systems.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-03-31',
    followers: 920,
    twitter: 'tanderson',
    website: 'https://tanderson.dev',
    linkedin: 'thomas-anderson',
    github: 'tanderson'
  },
  {
    id: 'maker41',
    name: 'Olivia Brown',
    role: 'Product Designer',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    bio: 'Creating user-centered products.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-04-01',
    followers: 880,
    twitter: 'oliviabrown',
    website: 'https://oliviabrown.design',
    linkedin: 'olivia-brown',
    github: 'oliviabrown'
  },
  {
    id: 'maker42',
    name: 'William Zhang',
    role: 'Data Scientist',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
    bio: 'Turning data into insights.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-02',
    followers: 1050,
    twitter: 'williamzhang',
    website: 'https://williamzhang.ai',
    linkedin: 'william-zhang',
    github: 'williamzhang'
  },
  {
    id: 'maker43',
    name: 'Sophie Turner',
    role: 'Brand Designer',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop',
    bio: 'Creating memorable brand identities.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-04-03',
    followers: 790,
    twitter: 'sophieturner',
    website: 'https://sophieturner.design',
    linkedin: 'sophie-turner',
    github: 'sophieturner'
  },
  {
    id: 'maker44',
    name: 'Lucas Rodriguez',
    role: 'Full Stack Developer',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    bio: 'Building end-to-end solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-04',
    followers: 970,
    twitter: 'lucasrodriguez',
    website: 'https://lucasrodriguez.dev',
    linkedin: 'lucas-rodriguez',
    github: 'lucasrodriguez'
  },
  {
    id: 'maker45',
    name: 'Ava Thompson',
    role: 'Growth Manager',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
    bio: 'Scaling products and teams.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-04-05',
    followers: 840,
    twitter: 'avathompson',
    website: 'https://avathompson.growth',
    linkedin: 'ava-thompson',
    github: 'avathompson'
  },
  {
    id: 'maker46',
    name: 'Nathan Park',
    role: 'Cloud Architect',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    bio: 'Designing cloud-native solutions.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-06',
    followers: 1150,
    twitter: 'nathanpark',
    website: 'https://nathanpark.cloud',
    linkedin: 'nathan-park',
    github: 'nathanpark'
  },
  {
    id: 'maker47',
    name: 'Maya Patel',
    role: 'UX Researcher',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=400&fit=crop',
    bio: 'Understanding user behavior.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: true,
    joinedDate: '2024-04-07',
    followers: 730,
    twitter: 'mayapatel',
    website: 'https://mayapatel.research',
    linkedin: 'maya-patel',
    github: 'mayapatel'
  },
  {
    id: 'maker48',
    name: 'Benjamin Lee',
    role: 'Product Manager',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    bio: 'Shipping impactful products.',
    category: 'Marketing',
    makerCategory: 'Marketing',
    isVerified: true,
    joinedDate: '2024-04-08',
    followers: 960,
    twitter: 'benjaminlee',
    website: 'https://benjaminlee.product',
    linkedin: 'benjamin-lee',
    github: 'benjaminlee'
  },
  {
    id: 'maker49',
    name: 'Grace Chen',
    role: 'Motion Designer',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop',
    bio: 'Creating engaging animations.',
    category: 'Designer',
    makerCategory: 'Designer',
    isVerified: false,
    joinedDate: '2024-04-09',
    followers: 820,
    twitter: 'gracechen',
    website: 'https://gracechen.design',
    linkedin: 'grace-chen',
    github: 'gracechen'
  },
  {
    id: 'maker50',
    name: 'Alexander White',
    role: 'Security Analyst',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
    bio: 'Protecting digital assets.',
    category: 'Developer',
    makerCategory: 'Developer',
    isVerified: true,
    joinedDate: '2024-04-10',
    followers: 890,
    twitter: 'alexwhite',
    website: 'https://alexwhite.security',
    linkedin: 'alexander-white',
    github: 'alexwhite'
  }
]

// Mock data for UI only - will be replaced with real data fetching
export const MOCK_APPS: App[] = [
  {
    id: '1',
    name: 'Figma',
    tagline: 'The collaborative interface design tool',
    description: 'A collaborative design tool for creating user interfaces, mobile apps, and websites with a wide range of features, including vector editing tools, prototyping, and version control, all in a cloud-based platform.',
    imageUrl: 'https://ph-files.imgix.net/db00a7a1-6778-4e51-a953-de5a9a339bc9.jpeg',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 345,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 24,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      website: 'https://browseragent.example.com',
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'maker-john',
        name: 'John Doe',
        role: 'Founder & Product Designer',
        avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
      {
        id: 'maker-jane',
        name: 'Jane Smith',
        role: 'Full Stack Developer',
        avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
        bio: 'Building scalable web applications with modern technologies.',
        category: 'Developer',
        joinedDate: '2024-02-01',
        followers: 850,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 12500,
      activeUsers: 5300,
      avgRating: 4.8,
    }
  },
  {
    id: '2',
    name: 'OpenAI',
    tagline: 'APIs and tools for building AI products',
    description: 'The most powerful platform for building AI products. Build and scale AI experiences powered by industry-leading models and tools.',
    imageUrl: 'https://ph-files.imgix.net/f904aec8-e324-4aed-ae3b-ff68795ce44f.png',
    coverImage: 'https://picsum.photos/1920/400?random=2',
    screenshots: [
      'https://picsum.photos/800/450?random=21',
      'https://picsum.photos/800/450?random=22',
      'https://picsum.photos/800/450?random=23',
    ],
    votes: 243,
    tags: ['Artificial Intelligence', 'Search'],
    commentsCount: 3,
    badges: ['new'],
    technologies: ['Python', 'PyTorch', 'TensorFlow', 'Google Cloud'],
    launchDate: '2024-01-20',
    updates: [
      { date: '2024-02-28', version: '1.0.1', description: 'Improved response accuracy and reduced latency' },
    ],
    externalLinks: {
      website: 'https://browseragent.example.com',
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
    },
    makers: [
      {
        id: 'maker-sarah',
        name: 'Sarah Williams',
        role: 'UI/UX Designer',
        avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
        bio: 'Creating delightful user experiences through thoughtful design.',
        category: 'Designer',
        joinedDate: '2024-02-15',
        followers: 920,
        isVerified: true
      },
      {
        id: 'maker-david',
        name: 'David Chen',
        role: 'Product Manager',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        bio: 'Bridging the gap between business needs and user experience.',
        category: 'Other',
        joinedDate: '2024-01-20',
        followers: 1500,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 35000,
      avgRating: 4.6,
    }
  },
  {
    id: '3',
    name: 'Vercel',
    tagline: 'The frontend cloud. Creators of Next.js.',
    description: 'Vercel provides the developer tools and cloud infrastructure to build, scale, and secure a faster, more personalized web.',
    imageUrl: 'https://ph-files.imgix.net/593ff5e2-9d11-491c-ab63-9e929e894214.jpeg',
    coverImage: 'https://picsum.photos/1920/400?random=3',
    screenshots: [
      'https://picsum.photos/800/450?random=31',
      'https://picsum.photos/800/450?random=32',
    ],
    votes: 200,
    tags: ['Productivity', 'User Experience', 'Tech'],
    commentsCount: 9,
    badges: ['trending'],
    technologies: ['Swift', 'Core ML', 'Natural Language Processing'],
    launchDate: '2023-09-05',
    updates: [
      { date: '2023-11-10', version: '1.1.0', description: 'Added support for additional languages' },
      { date: '2024-01-20', version: '1.2.0', description: 'Improved performance and reduced memory usage' },
    ],
    externalLinks: {
      website: 'https://grammarpaw.example.com',
      appStore: 'https://apps.apple.com/example-grammarpaw',
    },
    makers: [
      {
        id: 'maker-david',
        name: 'David Kim',
        role: 'Founder',
        avatar: '/avatars/avatar-4.png',
        bio: 'Building innovative language tools for developers',
        category: 'Developer',
        joinedDate: '2023-12-01',
        followers: 750,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 8700,
      avgRating: 4.7,
    }
  },
  {
    id: '4',
    name: 'Notion',
    tagline: 'The all-in-one workspace',
    description: 'Notion is an all-in-one workspace that combines note-taking, project management, and task organization. It allows users to create customized databases, documents, and calendars to streamline their personal and professional workflows.',
    imageUrl: 'https://ph-files.imgix.net/ff3e2acf-884a-4f4c-a383-6edfe3de0d88.png',
    coverImage: 'https://picsum.photos/1920/400?random=4',
    screenshots: [
      'https://picsum.photos/800/450?random=41',
      'https://picsum.photos/800/450?random=42',
      'https://picsum.photos/800/450?random=43',
    ],
    votes: 193,
    tags: ['SaaS', 'Developer Tools', 'Artificial Intelligence'],
    commentsCount: 17,
    technologies: ['JavaScript', 'Python', 'Docker', 'Kubernetes'],
    launchDate: '2023-11-01',
    updates: [
      { date: '2024-01-15', version: '1.1.0', description: 'Added support for advanced authentication methods' },
    ],
    externalLinks: {
      website: 'https://interlify.example.com',
      github: 'https://github.com/example/interlify',
    },
    makers: [
      {
        id: 'maker-sarah',
        name: 'Sarah Johnson',
        role: 'Co-founder',
        avatar: '/avatars/avatar-5.png',
        bio: 'Marketing expert with a passion for AI',
        category: 'Marketing',
        joinedDate: '2023-11-15',
        followers: 920,
        isVerified: true
      },
      {
        id: 'maker-michael',
        name: 'Michael Lee',
        role: 'Co-founder',
        avatar: '/avatars/avatar-6.png',
        bio: 'Full-stack developer specializing in AI integrations',
        category: 'Developer',
        joinedDate: '2023-11-15',
        followers: 840,
        isVerified: false
      }
    ],
    metrics: {
      activeUsers: 2800,
    }
  },
  {
    id: '5',
    name: 'Supabase',
    tagline: 'The open source Firebase alternative',
    description: 'Supabase is an open-source backend-as-a-service that provides real-time databases, authentication, and API services. It enables developers to build and scale applications quickly without managing server infrastructure.',
    imageUrl: 'https://ph-files.imgix.net/8dff2ac5-c4f0-4b02-9055-a2a0019f139c.jpeg',
    coverImage: 'https://picsum.photos/1920/400?random=5',
    screenshots: [
      'https://picsum.photos/800/450?random=51',
      'https://picsum.photos/800/450?random=52',
    ],
    votes: 177,
    tags: ['Newsletters', 'Growth Hacking', 'Advertising'],
    commentsCount: 5,
    badges: ['new'],
    technologies: ['React', 'Next.js', 'Node.js', 'PostgreSQL'],
    launchDate: '2024-02-01',
    externalLinks: {
      website: 'https://directsponsorships.example.com',
    },
    makers: [
      {
        id: 'maker-tyler',
        name: 'Tyler Wilson',
        role: 'Product Manager',
        avatar: '/avatars/avatar-7.png',
        bio: 'Product leader focused on creator economy',
        category: 'Marketing',
        joinedDate: '2024-01-10',
        followers: 680,
        isVerified: false
      }
    ],
    metrics: {
      activeUsers: 1200,
    }
  },
  {
    id: '6',
    name: 'Slack',
    tagline: 'Team communication and collaboration platform',
    description: 'Slack is an application that helps teams communicate and work together by combining messaging, file sharing, and app integrations in one place. It makes it easy for teams to stay connected and work efficiently, whether they are in the office or working remotely.',
    imageUrl: 'https://ph-files.imgix.net/2f06cf02-5fa1-4b17-8246-8b4499d50e33.jpeg',
    coverImage: 'https://picsum.photos/1920/400?random=6',
    screenshots: [
      'https://picsum.photos/800/450?random=61',
      'https://picsum.photos/800/450?random=62',
    ],
    votes: 165,
    tags: ['Developer Tools', 'Productivity', 'AI'],
    commentsCount: 12,
    badges: ['trending'],
    technologies: ['TypeScript', 'Python', 'Machine Learning'],
    launchDate: '2024-01-05',
    externalLinks: {
      website: 'https://devflow.example.com',
      github: 'https://github.com/example/devflow',
    },
    makers: [
      {
        id: 'maker-alex',
        name: 'Alex Rivera',
        role: 'Founder & Frontend Developer',
        avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop',
        bio: 'Frontend developer passionate about developer tools',
        category: 'Developer',
        joinedDate: '2024-01-05',
        followers: 950,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 3500,
      avgRating: 4.9,
    }
  },
  {
    id: '7',
    name: 'Linear',
    tagline: 'Purpose-built for planning and building products',
    description: 'Linear is a system for modern software development. Streamline issues, projects, and product roadmaps. Linear is the tool of choice for tens of thousands of ambitious product teams, including companies such as Vercel, CashApp, and Perplexity.',
    imageUrl: 'https://ph-files.imgix.net/9d9aa008-ca0e-4f10-84a1-211ae6875f45.png',
    coverImage: 'https://picsum.photos/1920/400?random=7',
    screenshots: [
      'https://picsum.photos/800/450?random=71',
      'https://picsum.photos/800/450?random=72',
    ],
    votes: 142,
    tags: ['Design', 'Productivity', 'Collaboration'],
    commentsCount: 8,
    technologies: ['React', 'Firebase', 'TailwindCSS'],
    launchDate: '2024-02-10',
    externalLinks: {
      website: 'https://designvault.example.com',
      appStore: 'https://apps.apple.com/example-designvault',
    },
    makers: [
      {
        id: 'maker-sophia',
        name: 'Sophia Wang',
        role: 'Interaction Designer',
        avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        bio: 'Creating delightful interactive experiences',
        category: 'Designer',
        joinedDate: '2024-02-10',
        followers: 760,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 5200,
      avgRating: 4.7,
    }
  },
  {
    id: '8',
    name: 'Cursor',
    tagline: 'The AI Code Editor',
    description: 'Built to make you extraordinarily productive, Cursor is the best way to code with AI.',
    imageUrl: 'https://ph-files.imgix.net/ada2695b-e20b-4c1b-b04a-e0fbd9daf466.png',
    coverImage: 'https://picsum.photos/1920/400?random=8',
    screenshots: [
      'https://picsum.photos/800/450?random=81',
      'https://picsum.photos/800/450?random=82',
    ],
    votes: 198,
    tags: ['Productivity', 'AI', 'Task Management'],
    commentsCount: 15,
    badges: ['trending'],
    technologies: ['React Native', 'Node.js', 'MongoDB'],
    launchDate: '2024-01-15',
    externalLinks: {
      website: 'https://taskmaster.example.com',
      appStore: 'https://apps.apple.com/example-taskmaster',
      playStore: 'https://play.google.com/store/example-taskmaster',
    },
    makers: [
      {
        id: 'maker-william',
        name: 'William Zhang',
        role: 'Data Scientist',
        avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=400&h=400&fit=crop',
        bio: 'Turning data into insights',
        category: 'Developer',
        joinedDate: '2024-01-15',
        followers: 1050,
        isVerified: true
      }
    ],
    metrics: {
      downloads: 15000,
      activeUsers: 8200,
      avgRating: 4.8,
    }
  },
  {
    id: '9',
    name: 'Stripe',
    tagline: 'Financial infrastructure for the internet',
    description: 'Accept payments, send payouts, automate financial processes, and ultimately grow revenue.',
    imageUrl: 'https://ph-files.imgix.net/7a01a00b-d41d-4367-b44e-e1d0a672819b.jpeg',
    coverImage: 'https://picsum.photos/1920/400?random=9',
    screenshots: [
      'https://picsum.photos/800/450?random=91',
      'https://picsum.photos/800/450?random=92',
    ],
    votes: 156,
    tags: ['Social Media', 'Marketing', 'AI'],
    commentsCount: 11,
    technologies: ['Vue.js', 'Python', 'PostgreSQL'],
    launchDate: '2024-02-20',
    externalLinks: {
      website: 'https://socialboost.example.com',
    },
    makers: [
      {
        id: 'maker-ava',
        name: 'Ava Thompson',
        role: 'Growth Manager',
        avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=400&h=400&fit=crop',
        bio: 'Scaling products and teams',
        category: 'Marketing',
        joinedDate: '2024-02-20',
        followers: 840,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 4200,
      avgRating: 4.6,
    }
  },
  {
    id: '10',
    name: 'Tailwind CSS',
    tagline: 'A utility-first CSS framework for rapid UI development',
    description: 'A highly customizable, low-level CSS framework that gives you all of the building blocks you need to build bespoke designs without any annoying opinionated styles you have to fight to override.',
    imageUrl: 'https://ph-files.imgix.net/829bdf09-bf73-4976-ae80-8eb1ec6b455d.png',
    coverImage: 'https://picsum.photos/1920/400?random=10',
    screenshots: [
      'https://picsum.photos/800/450?random=101',
      'https://picsum.photos/800/450?random=102',
    ],
    votes: 225,
    tags: ['Developer Tools', 'AI', 'Productivity'],
    commentsCount: 18,
    badges: ['trending'],
    technologies: ['TypeScript', 'Python', 'OpenAI'],
    launchDate: '2024-03-01',
    externalLinks: {
      website: 'https://codebuddy.example.com',
      github: 'https://github.com/example/codebuddy',
    },
    makers: [
      {
        id: 'maker-nathan',
        name: 'Nathan Park',
        role: 'Cloud Architect',
        avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
        bio: 'Designing cloud-native solutions',
        category: 'Developer',
        joinedDate: '2024-03-01',
        followers: 1150,
        isVerified: true
      }
    ],
    metrics: {
      activeUsers: 6800,
      avgRating: 4.9,
    }
  },
  {
    id: '11',
    name: 'Uopp',
    tagline: 'Marketplace con microvideos',
    description: 'Uopp es un marketplace basado en microvídeos para mejorar el engagement y la claridad al comprar y vender. Automatizamos muchos procesos y cuidamos mucho la experiencia de usuario.',
    imageUrl: '/apps/app-uopp.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 1100,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 7,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'javi-play',
        name: 'Javi Play85',
        role: 'Founder',
        avatar: '/users/user-javi-play.png',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Founder',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
    ],
    metrics: {
      downloads: 1000000,
      activeUsers: 150000,
      avgRating: 4.9,
    }
  },
  {
    id: '12',
    name: 'Dr. Green',
    tagline: 'Identifica y cuida tus plantas',
    description: 'Dr. Green te permite identificar, cuidar y diagnosticar tus plantas de forma automática usando inteligencia artificial. Solo tienes que hacer una foto: la app detecta qué planta es, te cuenta su historia, sus cuidados y te crea un plan de riego personalizado y te avisa cuando algo va mal.',
    imageUrl: '/apps/app-dr-green.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 1200,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 11,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'david-zafra',
        name: 'David Zafra',
        role: 'Founder & Product Designer',
        avatar: '/users/user-david-zafra.png',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
    ],
    metrics: {
      downloads: 1000000,
      activeUsers: 150000,
      avgRating: 4.9,
    }
  },
  {
    id: '13',
    name: 'TuTube',
    tagline: 'Por y para fans del podcast en España',
    description: 'La solución ideal para quienes quieren disfrutar de sus podcasts favoritos sin tener que bucear entre miles de vídeos sin relación.',
    imageUrl: '/apps/app-tutube.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 1300,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 15,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      website: 'https://tutube.vercel.app',
    },
    makers: [
      {
        id: 'saul-mases',
        name: 'Saul Mases',
        role: 'Founder & Product Designer',
        avatar: '/users/user-saul-mases.png',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
    ],
    metrics: {
      downloads: 1000000,
      activeUsers: 150000,
      avgRating: 4.9,
    }
  },
  {
    id: '14',
    name: 'NEU',
    tagline: 'Mapas de Esquí 3D',
    description: 'Descubre tu estación de esquí ideal. Planifica tu próxima aventura de esquí o snowboard en Andorra, España o Portugal con mapas en realidad aumentada.',
    imageUrl: '/apps/app-neu.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 1400,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 8,
    badges: ['trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      appStore: 'https://apps.apple.com/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'guillem-buix',
        name: 'Guillem Buix',
        role: 'Founder & Product Designer',
        avatar: '/users/user-guillem-buix.png',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
    ],
    metrics: {
      downloads: 12500,
      activeUsers: 5300,
      avgRating: 4.8,
    }
  },
  {
    id: '15',
    name: 'Habitz',
    tagline: 'Desarrolla mejores hábitos',
    description: 'Habitz es la herramienta integral de seguimiento de hábitos, súper fácil de usar, diseñada para ayudarte a crear buenos hábitos, superar los malos y ser constante con tus objetivos. Con seguimiento de rachas, recordatorios de hábitos, análisis de progreso y gamificación, mantener el rumbo nunca ha sido tan fácil.',
    imageUrl: '/apps/app-habitz.png',
    coverImage: 'https://picsum.photos/1920/400?random=1',
    screenshots: [
      'https://picsum.photos/800/450?random=11',
      'https://picsum.photos/800/450?random=12',
      'https://picsum.photos/800/450?random=13',
    ],
    votes: 1500,
    tags: ['SaaS', 'No-Code', 'Marketing automation'],
    commentsCount: 17,
    badges: ['top', 'trending'],
    technologies: ['React', 'Node.js', 'WebAssembly', 'TensorFlow.js'],
    launchDate: '2023-10-15',
    updates: [
      { date: '2023-12-01', version: '1.1.0', description: 'Added support for custom agent workflows' },
      { date: '2024-02-15', version: '1.2.0', description: 'Introduced template marketplace' },
    ],
    externalLinks: {
      appStore: 'https://apps.apple.com/example',
      playStore: 'https://play.google.com/store/example',
      github: 'https://github.com/example/browseragent',
    },
    makers: [
      {
        id: 'david-zafra',
        name: 'David Zafra',
        role: 'Founder & Product Designer',
        avatar: '/users/user-david-zafra.png',
        bio: 'Passionate about creating beautiful and functional user interfaces.',
        category: 'Designer',
        joinedDate: '2024-01-15',
        followers: 1200,
        isVerified: true
      },
    ],
    metrics: {
      downloads: 12500,
      activeUsers: 5300,
      avgRating: 4.8,
    }
  },

]

// Helper functions
export function getAllMakers(): Maker[] {
  return [...makers, ...ADDITIONAL_MAKERS]
}

export function getMakersByCategory(category: string): Maker[] {
  const allMakers = getAllMakers()
  if (category === 'All') return allMakers
  return allMakers.filter(maker => maker.category === category)
}

export function getAppById(id: string): App | undefined {
  return MOCK_APPS.find(app => app.id === id)
}

export function getAllApps(): App[] {
  return [...MOCK_APPS]
}

export function getTopApps(limit: number = 5): App[] {
  return [...MOCK_APPS]
    .sort((a, b) => b.votes - a.votes)
    .slice(0, limit)
}

export function getAppMakers(app: App): Maker[] {
  return app.makers as Maker[];
}